spring:
  application:
    name: service1
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
server.port: 8081
logging:
  level:
    org:
      zalando:
        logbook: TRACE
